openapi: 3.1.0
info:
  title: Spreadsheet Transaction Extractor API
  description: Upload a spreadsheet and extract transaction details.
  version: 1.0.0
servers:
  - url: https://financemanagement-47304.bubbleapps.io/version-test/api/1.1/wf
    description: Bubble API base
paths:
  /extract-transactions:
    post:
      operationId: extractTransactions
      summary: Extract transactions from a spreadsheet
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Bubble success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  response:
                    type: string
                    example: ok
