openapi: 3.1.0
info:
  title: Spreadsheet Transaction Extractor API
  description: |
    Upload a spreadsheet file (.xlsx or .csv) and extract transaction data.
  version: 1.0.0
servers:
  - url: https://postman-echo.com
    description: Temporary echo server for schema validation
paths:
  /extract-transactions:
    post:
      operationId: extractTransactions
      summary: Extract transactions from spreadsheet
      description: |
        Accepts a spreadsheet and returns transaction data including business name, transaction/charge details, and credit card used.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Extracted transaction data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    businessName:
                      type: string
                    transactionDate:
                      type: string
                      format: date
                    transactionAmount:
                      type: number
                      format: float
                    transactionCurrency:
                      type: string
                    chargeDate:
                      type: string
                      format: date
                    chargeAmount:
                      type: number
                      format: float
                    chargeCurrency:
                      type: string
                    creditCardUsed:
                      type: string
