openapi: 3.1.0
info:
  title: Spreadsheet Transaction Extractor API
  version: 1.0.0
servers:
  - url: https://kabalot.co.il/version-test/api/1.1/wf
    description: Bubble API
paths:
  /extract-transactions:
    post:
      operationId: extractTransactions
      summary: Extract transactions from uploaded spreadsheet
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Bubble response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  response:
                    type: string
