servers:
  - url: https://postman-echo.com
    description: Temporary echo server
paths:
  /post:
    post:
      operationId: extractTransactions
      summary: Dummy request for GPT import
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Dummy response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  response:
                    type: string
